services:
  # trashbot:
  #   image: ghcr.io/ggorg0/trashbot:master
  #   pull_policy: always
  #   build:
  #     context: .
  #   env_file: .env
  #   restart: unless-stopped
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    ports:
      - 27017:27017
    restart: always
    user: 1000:1000
